include: package:flutter_lints/flutter.yaml

analyzer:
  # strong-mode:
  #   implicit-dynamic: true
  errors:
    todo: ignore
    must_be_immutable: ignore
  exclude:
    - "**.freezed.dart"
    - "**.g.dart"
    - "**.gr.dart"
    - "**/generated_plugin_registrant.dart"

linter:
  rules:
    prefer_single_quotes: false
    avoid_function_literals_in_foreach_calls: false
    avoid_renaming_method_parameters: false
    prefer_relative_imports: true
    avoid_relative_lib_imports: true
    constant_identifier_names: false
    cascade_invocations: true
    implementation_imports: false
    one_member_abstracts: false
    overridden_fields: false
    prefer_const_constructors_in_immutables: false
    prefer_generic_function_type_aliases: false
    prefer_function_declarations_over_variables: false
    unnecessary_string_escapes: false
    use_key_in_widget_constructors: false
    directives_ordering: true
    require_trailing_commas: true
    unnecessary_getters_setters: false
    depend_on_referenced_packages: false
    no_leading_underscores_for_local_identifiers: false
    use_build_context_synchronously: false
    library_private_types_in_public_api: false
